spring:
    h2:
        console:
            path: /h2-console
            enabled: true
    application:
        name: library-service
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop

server:
    port: 8080

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

